[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
anturix = "6nwrr5Yj4KuevxokvBmtLKvLetJgcVTrgLnprVmw4h4x"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
