[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
anturix = "DBUe2tdR9esX7WxfPgTU9NTiUpB7anLkAnjocVukSEAZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
